use netrade;
drop table Trade;
drop table `StockOrder`;
drop table `Transaction`;
drop table hasStock;
drop table `Stock`;
drop table `Account`;
drop table `Client`;
drop table `Employee`;
drop table `Person`;
drop table `Location`;